# Generated by Django 5.1.4 on 2025-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.CharField(
                help_text="Добавьте ссылку на урок",
                max_length=255,
                verbose_name="Ссылка на урок",
            ),
        ),
    ]
